services:
  aci.webapp:
    image: aci.webapp
    build:
      context: .
      dockerfile: ACI.Webapp/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:80"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: aci_db
      POSTGRES_USER: admindb
      POSTGRES_PASSWORD: yma2578k
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
